version: '3.8'
services:
  app:
    build: 
        context: ./
        dockerfile: Dockerfile
    env_file: .env
    restart: always
    networks:
        - bridge_net
    volumes:
        - ./:/app
    ports:
        - "3000:8000"
networks:
    bridge_net:
        driver: bridge