version: '3.8'
services:
  app:
    build: 
        context: ./
        dockerfile: Dockerfile
    env_file: .env
    restart: always
    networks:
        - bridge_net
    volumes:
        - ./components:/app/components
        - ./pages:/app/pages
        - ./static:/app/static
        - ./store:/app/store
        - ./test:/app/test
    ports:
        - "3000:3000"
        - "24678:24678"
networks:
    bridge_net:
        driver: bridge